# Login
POST http://localhost:1234/login
Content-Type: application/json

{
  "username": "usuario123",
  "password": "password123"
}

### Registro
POST http://localhost:1234/register
Content-Type: application/json

{
  "nombre_usuario": "nuevoUsuario1",
  "email": "usuario@example.com",
  "contrasena": "password123"
}

### Obtener usuario por ID
GET http://localhost:1234/usuarios/6

### Actualizar usuario
PATCH http://localhost:1234/usuarios/1
Content-Type: application/json

{
  "username": "usuarioActualizado",
  "email": "actualizado@example.com"
}

### Actualizar contraseña
PATCH http://localhost:1234/usuarios/1/password
Content-Type: application/json

{
  "oldPassword": "password123",
  "newPassword": "nuevoPassword456"
}

### Eliminar usuario
DELETE http://localhost:1234/usuarios/1
