# Login
POST http://localhost:1234/login
Content-Type: application/json

{
  "username": "usuario123",
  "password": "password123"
}

### Registro
POST http://localhost:1234/register
Content-Type: application/json

{
  "nombre_usuario": "nuevoUsuari",
  "email": "usuario8@example1.com",
  "contrasena": "password1234"
}

### Crear tarea
POST http://localhost:1234/tareas
Content-Type: application/json

{
  "descripcion": "tarea de no se que",
  "valor":  10,
  "id_usuario": 6,
  "fecha_inicio": "2025-02-15",
  "fecha_fin": "2025-02-17",
  "estado": "Sin finalizar"
}

### Crear examen
POST http://localhost:1234/examenes
Content-Type: application/json

{
  "asignatura": "tlp",
  "nota":  10,
  "id_usuario": 6,
  "fecha": "2025-02-17"
}

### Crear proyecto
POST http://localhost:1234/proyectos
Content-Type: application/json

{
  "titulo": "trabajo de bien 23334",
  "id_usuario": 6,
  "descripcion": "uno dos tres",
  "fecha_entrega": "2025-02-18"
}

### Obtener usuario por ID
GET http://localhost:1234/usuarios/6

### Obtener tarea por ID 
GET http://localhost:1234/tareas/6

### Obtener proyecto por ID
GET http://localhost:1234/proyectos/1

### Obtener examen por ID
GET http://localhost:1234/examenes/1


### Obtener todas las tareas por ID de usuario
GET http://localhost:1234/usuarios/1/tareas

### Obtener proyectos por ID de usuario
GET http://localhost:1234/usuarios/1/proyectos

### Obtener examenes por ID de usuario
GET http://localhost:1234/usuarios/1/examenes

### Actualizar usuario
PATCH http://localhost:1234/usuarios/6
Content-Type: application/json

{
  "nombre_usuario": "usuarioActualizado2",
  "email": "actualizado2@example.com"
}

### Actualizar contraseña
PATCH http://localhost:1234/usuarios/1/password
Content-Type: application/json

{
  "oldPassword": "password123",
  "newPassword": "nuevoPassword456"
}

### Actualizar examen
PATCH http://localhost:1234/examenes/5
Content-Type: application/json

{
  "asignatura": "mates",
  "nota": 3.00,
  "fecha": "2025-02-08"
}

### Actualizar tarea
PATCH http://localhost:1234/tareas/1
Content-Type: application/json

{
  "descripcion": "Tarea actualizada",
  "valor": 30.00,
  "fecha_fin": "2025-02-11",
  "estado" : "Finalizado"
}

### Actualizar proyecto
PATCH http://localhost:1234/proyectos/1
Content-Type: application/json

{
  "titulo": "proyecto de biologia",
  "fecha_entrega": "2025-02-11"
}

### Eliminar usuario
DELETE http://localhost:1234/usuarios/4

### Eliminar tarea
DELETE http://localhost:1234/tareas/3

### Eliminar examen
DELETE http://localhost:1234/examenes/4