# Login
POST http://localhost:5000/login
Content-Type: application/json

{
  "nombre_usuario": "prueba14",
  "contrasena": "password500056"
}

### Registro
POST http://localhost:5000/register
Content-Type: application/json

{
  "nombre_usuario": "prueba14",
  "email": "usuario14@example1.com",
  "contrasena": "password500056"
}

### Crear tarea
POST http://localhost:5000/tareas/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
Content-Type: application/json

{
  "descripcion": "tarea de no se que 2",
  "valor":  10,
  "fecha_inicio": "2025-02-15",
  "fecha_fin": "2025-02-17",
  "estado": "Sin finalizar"
}

### Crear examen
POST http://localhost:5000/examenes/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
Content-Type: application/json

{
  "asignatura": "tlp",
  "nota":  10,
  "fecha": "2025-02-17"
}

### Crear proyecto
POST http://localhost:5000/proyectos/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
Content-Type: application/json

{
  "titulo": "trabajo de bien 23334",
  "descripcion": "uno dos tres",
  "fecha_entrega": "2025-02-18"
}

### crear tarea en proyecto
POST http://localhost:5000/proyectos/tarea/1/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
Content-Type: application/json

{
  "descripcion": "Tarea de prueba",
  "fecha_inicio": "2025-03-01",
  "fecha_fin": "2025-03-10",
  "estado": "Pendiente",
  "valor": 50.00
}


### asociar usuarios al proyecto
POST http://localhost:5000/proyectos/asociar/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
Content-Type: application/json

{
  "nombre_usuario" : "nuevoUsuario8"
}

### Obtener usuario por ID
GET http://localhost:5000/usuarios/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
### Obtener tarea por ID 
GET http://localhost:5000/tareas/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
### Obtener proyecto por ID
GET http://localhost:5000/proyectos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
### Obtener examen por ID
GET http://localhost:5000/examenes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8

### Obtener todas las tareas por ID de usuario
GET http://localhost:5000/usuarios/17/tareas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
### Obtener proyectos por ID de usuario
GET http://localhost:5000/usuarios/17/proyectos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
### Obtener examenes por ID de usuario
GET http://localhost:5000/usuarios/17/examenes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
### Actualizar usuario
PATCH http://localhost:5000/usuarios/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
Content-Type: application/json

{
  "nombre_usuario": "usuarioActualizado2",
  "email": "actualizado2@example.com"
}

### Actualizar contraseña
PATCH http://localhost:5000/usuarios/17/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
Content-Type: application/json

{
  "oldPassword": "password50005",
  "newPassword": "nuevoPassword456"
}

### Actualizar examen
PATCH http://localhost:5000/examenes/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
Content-Type: application/json

{
  "asignatura": "mates",
  "nota": 3.00,
  "fecha": "2025-02-08"
}

### Actualizar tarea
PATCH http://localhost:5000/tareas/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
Content-Type: application/json

{
  "descripcion": "Tarea actualizada",
  "valor": 30.00,
  "fecha_fin": "2025-02-11",
  "estado" : "Finalizado"
}

### Actualizar proyecto
PATCH http://localhost:5000/proyectos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8
Content-Type: application/json

{
  "titulo": "proyecto de biologia",
  "fecha_entrega": "2025-02-11"
}

### Eliminar usuario
DELETE http://localhost:5000/usuarios/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8

### Eliminar tarea
DELETE http://localhost:5000/tareas/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8

### Eliminar examen
DELETE http://localhost:5000/examenes/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5vbWJyZV91c3VhcmlvIjoicHJ1ZWJhMTQiLCJpYXQiOjE3Mzk3OTY0NjcsImV4cCI6MTczOTg4Mjg2N30.KvzjrXxiOhFo3VBz3xH2tkHu7BHB9nwIneBbf684Ql8